kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: docker:20
    commands:
      - docker-compose build

  - name: deploy
    image: docker:20
    commands:
      - docker-compose down
      - docker-compose up -d