name: CI/CD Pipeline

on:
  push:
    branches:
      - main # Запускается при пуше в ветку main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Установка Docker и Docker Compose
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install docker-compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      # Шаг 3: Логин в Docker Hub (опционально, если используете свои образы)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Шаг 4: Сборка Docker-образов
      - name: Build and push Docker images
        run: |
          docker-compose build

      # Шаг 5: Деплой
      - name: Deploy containers
        run: |
          docker-compose down
          docker-compose up -d
