name: CI/CD Pipeline

on:
  push:
    branches:
      - main # Запускается при пуше в ветку main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Логин в Docker Hub (опционально, если используете свои образы)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Шаг 3: Сборка Docker-образов
      - name: Build and push Docker images
        run: |
          docker-compose build

      # Шаг 4: Деплой
      - name: Deploy containers
        run: |
          docker-compose down
          docker-compose up -d
      # Шаг: Настройка SSH
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Шаг: Деплой на сервер
      - name: Deploy to server
        run: |
          ssh user@your-server-ip << 'EOF'
            cd /path/to/your/project
            docker-compose pull
            docker-compose down
            docker-compose up -d
          EOF