name: CI/CD Pipeline

on:
  push:
    branches:
      - main # Запускается при пуше в ветку main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Логин в Docker Hub (опционально, если используете свои образы)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Шаг 3: Сборка Docker-образов
      - name: Build and push Docker images
        run: |
          docker-compose build

      # Шаг 4: Деплой
      - name: Deploy containers
        run: |
          docker-compose down
          docker-compose up -d